name: Create Repo

on:
  issues:
    types: [opened, edited]

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Print issue title and body
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          
      - name: Process issue
        if: startsWith(github.event.issue.title, '[NEW_REPO]')
        run: |
          echo "Processing issue with title starting with [NEW_REPO]"
          echo "${{ github.event.issue.body }}"

      - name: Extract variables
        id: extract_variables
        run: |
            echo "${{ github.event.issue.body }}" > text.txt
            project_name=$(grep -Po '(?<=### project_name\n\n).*' text.txt)
            description=$(grep -Po '(?<=### description\n\n).*' text.txt)
            privacy_type=$(grep -Po '(?<=### privacy_type\n\n).*' text.txt)
            project_template=$(grep -Po '(?<=### project_template\n\n).*' text.txt)
            CI_CD=$(grep -Po '(?<=### CI_CD\n\n).*' text.txt)
            echo "::set-output name=project_name::$project_name"
            echo "::set-output name=description::$description"
            echo "::set-output name=privacy_type::$privacy_type"
            echo "::set-output name=project_template::$project_template"
            echo "::set-output name=CI_CD::$CI_CD"
      - name: Print extracted variables
        run: |
            echo "Project Name: ${{ steps.extract_variables.outputs.project_name }}"
            echo "Description: ${{ steps.extract_variables.outputs.description }}"
            echo "Privacy Type: ${{ steps.extract_variables.outputs.privacy_type }}"
            echo "Project Template: ${{ steps.extract_variables.outputs.project_template }}"
            echo "CI/CD: ${{ steps.extract_variables.outputs.CI_CD }}"