name: Create Repo

on:
  issues:
    types: [opened, edited]

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Print issue title and body
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          
      - name: Process issue
        if: startsWith(github.event.issue.title, '[NEW_REPO]')
        run: |
          echo "Processing issue with title starting with [NEW_REPO]"
          echo "${{ github.event.issue.body }}" > project_details.txt

          project_name=$(grep -A 2 "### project_name" project_details.txt | tail -n 1)
          description=$(grep -A 2 "### description" project_details.txt | tail -n 1)
          privacy_type=$(grep -A 2 "### privacy_type" project_details.txt | tail -n 1)
          project_template=$(grep -A 2 "### project_template" project_details.txt | tail -n 1)
          CI_CD=$(grep -A 2 "### CI_CD" project_details.txt | tail -n 1)
          
          echo "Project Name: $project_name"
          echo "Description: $description"
          echo "Privacy Type: $privacy_type"
          echo "Project Template: $project_template"
          echo "CI_CD: $CI_CD"

          echo "project_name=$project_name" >> $GITHUB_ENV
          echo "description=$description" >> $GITHUB_ENV
          echo "privacy_type=$privacy_type" >> $GITHUB_ENV
          echo "project_template=$project_template" >> $GITHUB_ENV
          echo "CI_CD=$CI_CD" >> $GITHUB_ENV

  create_repo:
    needs: process_issue
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[NEW_REPO]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Repo
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PROJECT_NAME: ${{ env.project_name }}
          DESCRIPTION: ${{ env.description }}

        run: |
          echo "Creating repo $PROJECT_NAME"
          echo "Description: $DESCRIPTION"
          gh repo create $PROJECT_NAME --private --add-readme=true -d "$DESCRIPTION"