# This is a basic workflow to help you get started with Actions

name: test Github App

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  github-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.SETUP_APP_ID }}
          application_private_key: ${{ secrets.SETUP_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Maua-Dev/ci_workflows_reusable
          toke: ${{ steps.get_workflow_token.outputs.token }}
          path: lib
      - name: get jwt
        working-directory: lib
        run: |
          ls -a
          token=$(./github-app-token.sh)
          echo $token
          echo "token=$token" >> $GITHUB_OUTPUT
        env:
          APP_ID: ${{ secrets.SETUP_APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.SETUP_APP_PRIVATE_KEY }}
      
      
