# This is a basic workflow to help you get started with Actions

name: test Github App

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  github-app:
    uses: maua-dev/ci_workflows_reusable/.github/workflows/github-app.yml@main
    with:
      secrets: inherit
      
